apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-pv
  labels:
    type: psql
#  namespace: psql-ns

spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /usr/k8s
    type: DirectoryOrCreate


