apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-pvc
#  namespace: psql-ns

spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi



